name: ci
on:
  push:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  🚀
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Install pnpm  🚀
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js  🚀
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: pnpm

      - name: Install Deps  🚀
        run: pnpm install --frozen-lockfile

      - name: Build project  🚀
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run build

      - name: copy README.md
        run: cp README.md dist
    needs: clear

  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Code coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
    needs: ci

  clear:
    name: clear
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚀
        uses: actions/checkout@v2
        with:
          repository: 'h7ml/Workflows-Cleaner'
          fetch-depth: 0
      - name: Set up Python 🚀
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: python cache 🚀
        uses: actions/cache@v2
        with:
          path: '~/.cache/pip'
          key: "${{ runner.os }}-pip-cache-${{ hashFiles('setup.cfg') }}"
          restore-keys: |
            "${{ runner.os }}-pip-cache-"
            "${{ runner.os }}-pip-"
      - name: Install pipenv 🚀
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXPIRE_TIME: '1h'
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv install
          pipenv run python run.py
